apiVersion: v1
kind: Pod
metadata:
  name: combine-pod
spec:
  containers:
    - name: example-container
      image: busybox
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: database_url
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: database_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: example-secret
              key: database_password
      command: ["sh", "-c", "while true; do echo $DATABASE_URL && echo $DATABASE_USER && echo $DATABASE_PASSWORD; sleep 3600; done"]
  restartPolicy: Never
