apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: example-container
          image: busybox
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: database_url
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: database_user
          command: ["sh", "-c", "while true; do echo DATABASE_URL=$DATABASE_URL; echo DATABASE_USER=$DATABASE_USER; echo DATABASE_PASSWORD=$DATABASE_PASSWORD; sleep 3600; done"]
      restartPolicy: Always
