apiVersion: v1
kind: Pod
metadata:
  name: practice-pod2
spec:
  containers:
    - name: practice-container
      image: busybox
      env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: practice-secret
              key: database_password
      command: ["sh", "-c", "while true; do echo $DATABASE_PASSWORD; sleep 3600; done"]
  restartPolicy: Never
